DROP TABLE RESTAURANT_SHIFT;
ALTER TABLE SHIFT ADD COLUMN MAXIMUM_GUESTS INT NOT NULL,
ADD COLUMN RESTAURANT_ID BIGINT NOT NULL;

ALTER TABLE SHIFT ADD CONSTRAINT FK_RESTAURANT_ID FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (ID) ON DELETE CASCADE;