ALTER TABLE RESTAURANT DROP COLUMN IMAGE;
ALTER TABLE RESTAURANT ADD COLUMN IMAGE VARCHAR(255);

ALTER TABLE MEAL DROP COLUMN IMAGE;
ALTER TABLE MEAL ADD COLUMN IMAGE VARCHAR(255);

ALTER TABLE D_USER DROP COLUMN IMAGE;
ALTER TABLE D_USER ADD COLUMN IMAGE VARCHAR(255);