CREATE TYPE EAT_IN_OR_TAKE_AWAY_ENUM AS ENUM ('EAT_IN', 'TAKE_AWAY');
ALTER TABLE D_ORDER
    ADD COLUMN EAT_IN_OR_TAKE_AWAY EAT_IN_OR_TAKE_AWAY_ENUM NOT NULL DEFAULT 'EAT_IN';
ALTER TABLE D_ORDER ADD COLUMN COMMENT VARCHAR(255);
