CREATE SEQUENCE FAST_ORDER_SEQ INCREMENT BY 100 START WITH 10000;
CREATE TABLE FAST_ORDER (
   ID BIGINT NOT NULL,
   USER_ID BIGINT NOT NULL,
   MEAL_ID BIGINT NOT NULL,
   RESTAURANT_ID BIGINT NOT NULL,
   SHIFT_ID BIGINT NOT NULL,
   EAT_IN_OR_TAKE_AWAY EAT_IN_OR_TAKE_AWAY_ENUM NOT NULL DEFAULT 'EAT_IN',
   COMMENT VARCHAR(255)
);
ALTER TABLE FAST_ORDER ADD CONSTRAINT PK_FAST_ORDER PRIMARY KEY (ID),
ADD CONSTRAINT FK_FAST_ORDER_SHIFT FOREIGN KEY (SHIFT_ID) REFERENCES SHIFT (ID) ON DELETE CASCADE,
ADD CONSTRAINT FK_FAST_ORDER_MEAL FOREIGN KEY (MEAL_ID) REFERENCES MEAL (ID) ON DELETE CASCADE,
ADD CONSTRAINT FK_FAST_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES D_USER (ID) ON DELETE CASCADE;