CREATE TABLE USER_FAVORITES (
  USER_ID BIGINT NOT NULL,
  FAVORITE_USER_ID BIGINT NOT NULL,
  PRIMARY KEY (USER_ID, FAVORITE_USER_ID),
  CONSTRAINT FK_USER_FAVORITE_USER FOREIGN KEY (USER_ID) REFERENCES D_USER(ID),
  CONSTRAINT FK_FAVORITE_USER FOREIGN KEY (FAVORITE_USER_ID) REFERENCES D_USER(ID)
);
