CREATE TYPE user_role AS ENUM ('Admin', 'User');
CREATE SEQUENCE D_USER_SEQ INCREMENT BY 100 START WITH 10000;
CREATE TABLE D_USER
(ID BIGINT NOT NULL,
 FIRST_NAME CHARACTER VARYING(64),
  LAST_NAME CHARACTER VARYING(64),
  EMAIL CHARACTER VARYING(128),
  IMAGE bytea,
  ROLE user_role
);
ALTER TABLE D_USER ADD CONSTRAINT PK_USER PRIMARY KEY (ID);