CREATE SEQUENCE RESTAURANT_SEQ INCREMENT BY 100 START WITH 10000;
CREATE TABLE RESTAURANT (
 ID BIGINT  NOT NULL,
 NAME VARCHAR(255) NOT NULL,
 PHOTO bytea,
 CITY VARCHAR(255)
);
ALTER TABLE RESTAURANT ADD CONSTRAINT PK_RESTAURANT PRIMARY KEY (ID);