CREATE SEQUENCE SHIFT_SEQ INCREMENT BY 100 START WITH 10000;
CREATE TABLE SHIFT (
 ID NUMERIC(19,0)  NOT NULL,
 NAME VARCHAR(100) NOT NULL
);
ALTER TABLE SHIFT ADD CONSTRAINT PK_SHIFT PRIMARY KEY (ID);