CREATE SEQUENCE RESTAURANT_SHIFT_SEQ INCREMENT BY 100 START WITH 10000;
CREATE TABLE RESTAURANT_SHIFT (
 RESTAURANT_ID BIGINT NOT NULL,
 SHIFT_ID BIGINT NOT NULL,
 MAXIMUM_GUESTS INT
);
ALTER TABLE RESTAURANT_SHIFT ADD CONSTRAINT PK_RESTAURANT_SHIFT PRIMARY KEY(RESTAURANT_ID, SHIFT_ID),
ADD CONSTRAINT FK_SHIFT_ID FOREIGN KEY (SHIFT_ID) REFERENCES SHIFT (ID) ON DELETE CASCADE;