CREATE TYPE proposal_status AS ENUM ('Active', 'Closed', 'Canceled');
CREATE SEQUENCE DINNER_PROPOSAL_SEQ INCREMENT BY 100 START WITH 10000;
CREATE TABLE DINNER_PROPOSAL (
 ID NUMERIC(19,0) NOT NULL,
 INITIATOR_USER_ID NUMERIC(19,0) NOT NULL,
 RESTAURANT_ID NUMERIC(19,0) NOT NULL,
 SHIFT_ID NUMERIC(19,0) NOT NULL,
 CREATED_AT TIMESTAMP,
 STATUS proposal_status
);
ALTER TABLE DINNER_PROPOSAL ADD CONSTRAINT PK_DINNER_PROPOSAL PRIMARY KEY (ID),
ADD CONSTRAINT FK_DINNER_SHIFT FOREIGN KEY (SHIFT_ID) REFERENCES SHIFT (ID) ON DELETE CASCADE,
ADD CONSTRAINT FK_DINNER_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (ID) ON DELETE CASCADE,
ADD CONSTRAINT FK_DINNER_USER FOREIGN KEY (INITIATOR_USER_ID) REFERENCES D_USER (ID) ON DELETE CASCADE;

