CREATE TYPE participant_status AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED');
CREATE SEQUENCE DINNER_PROPOSAL_PARTICIPANT_SEQ INCREMENT BY 100 START WITH 10000;
CREATE TABLE DINNER_PROPOSAL_PARTICIPANT (
 ID NUMERIC(19,0) NOT NULL,
 PROPOSAL_ID NUMERIC(19,0) NOT NULL,
 USER_ID NUMERIC(19,0) NOT NULL,
 STATUS participant_status
);
ALTER TABLE DINNER_PROPOSAL_PARTICIPANT ADD CONSTRAINT PK_DINNER_PROPOSAL_PARTICIPANT PRIMARY KEY (ID),
ADD CONSTRAINT FK_DINNER_PARTICIPANT_PROPOSAL FOREIGN KEY (PROPOSAL_ID) REFERENCES DINNER_PROPOSAL (ID) ON DELETE CASCADE,
ADD CONSTRAINT FK_DINNER_PARTICIPANT_USER FOREIGN KEY (USER_ID) REFERENCES D_USER (ID) ON DELETE CASCADE;