CREATE SEQUENCE MEAL_SEQ INCREMENT BY 100 START WITH 10000;
CREATE TABLE MEAL (
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    IMAGE bytea,
    AVG_RATING DECIMAL(2,1),
    RESTAURANT_ID BIGINT NOT NULL
);
ALTER TABLE MEAL ADD CONSTRAINT PK_MEAL PRIMARY KEY (ID),
ADD CONSTRAINT FK_MEAL_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (ID) ON DELETE CASCADE;