CREATE SEQUENCE ORDER_SEQ INCREMENT BY 100 START WITH 10000;
CREATE TABLE D_ORDER (
 ID BIGINT NOT NULL,
 USER_ID BIGINT NOT NULL,
 MEAL_ID BIGINT NOT NULL,
 SHIFT_ID BIGINT NOT NULL,
 PROPOSAL_ID BIGINT
);
ALTER TABLE D_ORDER ADD CONSTRAINT PK_ORDER PRIMARY KEY (ID),
ADD CONSTRAINT FK_ORDER_SHIFT FOREIGN KEY (SHIFT_ID) REFERENCES SHIFT (ID) ON DELETE CASCADE,
ADD CONSTRAINT FK_ORDER_MEAL FOREIGN KEY (MEAL_ID) REFERENCES MEAL (ID) ON DELETE CASCADE,
ADD CONSTRAINT FK_ORDER_PROPOSAL FOREIGN KEY (PROPOSAL_ID) REFERENCES DINNER_PROPOSAL (ID) ON DELETE CASCADE,
ADD CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES D_USER (ID) ON DELETE CASCADE;