CREATE SEQUENCE MEAL_RATING_SEQ INCREMENT BY 100 START WITH 10000;
CREATE TABLE MEAL_RATING (
 ID BIGINT NOT NULL,
 USER_ID BIGINT NOT NULL,
 MEAL_ID BIGINT NOT NULL,
 RATING INT CHECK (RATING BETWEEN 1 AND 5)
);
ALTER TABLE MEAL_RATING ADD CONSTRAINT PK_MEAL_RATING PRIMARY KEY (ID),
ADD CONSTRAINT FK_MEAL_RATING_MEAL FOREIGN KEY (MEAL_ID) REFERENCES MEAL (ID) ON DELETE CASCADE,
ADD CONSTRAINT FK_MEAL_RATING_USER FOREIGN KEY (USER_ID) REFERENCES D_USER (ID) ON DELETE CASCADE;